# arxivの学問領域の指定
subject: 'cat:astro-ph.GA or cat:astro-ph.HE'

# 検索キーワード
keywords:
        SS433: 5
        SS 433: 5
        W50: 5
        jet: 4
        magnetic field: 2
        galaxy cluster: 2
        machine learning: 4
        deep learning: 4
        

# 通知の閾値
score_threshold: 0
